### ISSUE TITLE
What do I need to do to release a new version on conda?

### ISSUE THREAD

**Issue by jluethi** [conda-forge/napari-feature-classifier-feedstock#1]
### Comment:

I just released the 0.0.2 version on pypi (see https://pypi.org/project/napari-feature-classifier/). What do I need to do for this version to also come to conda? 

Also, last time we had to deactivate `pip check`, because I still had sklearn as a dependency instead of scikit-learn. That's corrected now. How would we thus activate it now? See discussion here: https://github.com/conda-forge/staged-recipes/pull/19234#issuecomment-1154420991

cc maybe @goanpeca ?

Thanks for the help already in advance!

**Comment by goanpeca** [comment]
hi @jluethi, https://github.com/conda-forge/napari-feature-classifier-feedstock/pull/2 was opened yesterday so it takes a little bit after the release on pypi to get a PR automatically generated in here

You can edit the file manually on the github interface to enable pip check :)

I will do it now!

Cheers and thanks for the ping

**Comment by goanpeca** [comment]
The PR has been merged, there should be a version available soon 

closing!

**Comment by jluethi** [comment]
Thanks a lot @goanpeca ! I'll be more patient next time! :)
